# Generated by Django 3.0.4 on 2020-06-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200616_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Date',
        ),
        migrations.AddField(
            model_name='task',
            name='Owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolist.User'),
            preserve_default=False,
        ),
    ]
