# Generated by Django 3.0.4 on 2020-06-16 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20200616_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 11, 3, 5, 98866)),
        ),
    ]
