# Generated by Django 3.0.4 on 2020-06-16 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 11, 4, 57, 762399)),
        ),
    ]
