# Generated by Django 3.0.4 on 2020-06-16 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20200616_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Time',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 5, 37, 53, 869457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 11, 7, 53, 869457)),
        ),
    ]
