# Generated by Django 3.0.4 on 2020-06-16 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20200616_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 11, 10, 15, 455048)),
        ),
    ]
