# Generated by Django 3.0.4 on 2020-06-16 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20200616_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='UserId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 12, 33, 4, 365694)),
        ),
    ]
