# Generated by Django 3.0.4 on 2020-06-16 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_auto_20200616_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 12, 34, 11, 377666)),
        ),
    ]
